// Existing Order Constants
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST";
export const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS";
export const MY_ORDERS_FAIL = "MY_ORDERS_FAIL";

export const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST";
export const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS";
export const ALL_ORDERS_FAIL = "ALL_ORDERS_FAIL";

export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_RESET = "UPDATE_ORDER_RESET";
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_RESET = "DELETE_ORDER_RESET";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

// Delivery Agent Management Constants
export const ASSIGN_AGENT_REQUEST = "ASSIGN_AGENT_REQUEST";
export const ASSIGN_AGENT_SUCCESS = "ASSIGN_AGENT_SUCCESS";
export const ASSIGN_AGENT_RESET = "ASSIGN_AGENT_RESET";
export const ASSIGN_AGENT_FAIL = "ASSIGN_AGENT_FAIL";

export const MY_DELIVERIES_REQUEST = "MY_DELIVERIES_REQUEST";
export const MY_DELIVERIES_SUCCESS = "MY_DELIVERIES_SUCCESS";
export const MY_DELIVERIES_FAIL = "MY_DELIVERIES_FAIL";

export const UPDATE_DELIVERY_REQUEST = "UPDATE_DELIVERY_REQUEST";
export const UPDATE_DELIVERY_SUCCESS = "UPDATE_DELIVERY_SUCCESS";
export const UPDATE_DELIVERY_RESET = "UPDATE_DELIVERY_RESET";
export const UPDATE_DELIVERY_FAIL = "UPDATE_DELIVERY_FAIL";

// Return Order Constants
export const RETURN_ORDER_REQUEST = "RETURN_ORDER_REQUEST";
export const RETURN_ORDER_SUCCESS = "RETURN_ORDER_SUCCESS";
export const RETURN_ORDER_FAIL = "RETURN_ORDER_FAIL";
export const RETURN_ORDER_RESET = "RETURN_ORDER_RESET";

export const UPDATE_RETURN_STATUS_REQUEST = "UPDATE_RETURN_STATUS_REQUEST";
export const UPDATE_RETURN_STATUS_SUCCESS = "UPDATE_RETURN_STATUS_SUCCESS";
export const UPDATE_RETURN_STATUS_FAIL = "UPDATE_RETURN_STATUS_FAIL";
export const UPDATE_RETURN_STATUS_RESET = "UPDATE_RETURN_STATUS_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";